module.exports = {
    "AUS-sky": "Austin",
    "DFWA-sky": "Dallas",
    "HOUA-sky": "Houston",
    "AMMA-sky": "Amman",
    "BJSA-sky": "Beijing",
    "CUN-sky": "Cancun",
    "CUZ-sky": "Cuzco",
    "DEL-sky": "New Delhi",
    "HRE-sky": "Harare",
    "MEX-sky": "Mexico City",
    "PHXA-sky": "Phoenix",
    "REYK-sky": "Reykjavik",
    "RIOA-sky": "Rio de Janiero",
    "ROME-sky": "Rome",
    "SYD-sky": "Sydney",
    "LOND-sky": "London",
    "BKKT-sky": "Bangkok",
    "PARI-sky": "Paris",
    "DXBA-sky": "Dubai",
    "ISTA-sky": "Istanbul",
    "SIN-sky": "Singapore",
    "SELA-sky": "Seoul",
    "LAX-sky": "Los Angeles",
    "CHIA-sky": "Chicago",
    "DEN-sky": "Denver",
    "LAS-sky": "Las Vegas",
    "SFO-sky": "San Francisco",
    "NYCA-sky": "New York",
    "MIAA-sky": "Miami",
    "TYOA-sky": "Tokyo",
    "HKG-sky": "Hong Kong",
    "FLR-sky": "Florence",
    "BERL-sky": "Berlin",
    "LIM-sky": "Lima",
    "OGG-sky": "Maui",
    "NAN-sky": "Fiji",
    "JMK-sky": "Mykonos",
    "BKKT-sky": "Ko Phi Phi",
    "IBZ-sky": "Ibiza",
    "AUA-sky": "Aruba",
    "GCM-sky": "Grand Cayman"
};

