module.exports = {
    "AMMA-sky": "Amman",
    "BJSA-sky": "Beijing",
    "CUN-sky": "Cancun",
    "CUZ-sky": "Cuzco",
    "DEL-sky": "New Delhi",
    "HRE-sky": "Harare",
    "MEX-sky": "Mexico City",
    "PHXA-sky": "Phoenix",
    "REYK-sky": "Reykjavik",
    "RIOA-sky": "Rio de Janiero",
    "ROME-sky": "Rome",
    "SYD-sky": "Sydney",
    "DFWA-sky": "Dallas",
    "HOUA-sky": "Houston",
    "HRE-sky": "Harare",
    "REYK-sky": "Reykjavik",
    "PHXA-sky": "Phoenix",
    "SYD-sky": "Sydney",
    "MEX-sky": "Mexico City",
    "DEL-sky": "New Delhi",
    "LOND-sky": "London",
    "BKKT-sky": "Bangkok",
    "PARI-sky": "Paris",
    "DXBA-sky": "Dubai",
    "ISTA-sky": "Istanbul",
    "SIN-sky": "Singapore",
    "SELA-sky": "Seoul",
    "LAX-sky": "Los Angeles",
    "CHIA-sky": "Chicago",
    "DEN-sky": "Denver",
    "LAS-sky": "Las Vegas",
    "SFO-sky": "San Francisco",
    "NYCA-sky": "New York City",
    "MIAA-sky": "Miami"
};
